from pathlib import Path
import re
path = Path(r'f:\REACT\MINI-PROJECTS\WebsiteBuilder\lovable\src\lib\builder\preview.ts')
text = path.read_text(encoding='utf-8')

replacements = {
    'dragstart': (r"document\.addEventListener\('dragstart', e => \{[\s\S]*?\n  \}\);\n", 
"  document.addEventListener('dragstart', e => {\n    try {\n      const target = getEventTarget(e);\n      const wrapper = target && target.closest ? target.closest('[data-container-child-wrapper], [data-wto-widget-element-key]') : null;\n      if (wrapper && currentSelection && currentSelection.sectionId && currentSelection.widgetId && (currentSelection.childId || currentSelection.elementKey)) {\n        currentDragSource = {\n          sectionId: currentSelection.sectionId,\n          widgetId: currentSelection.widgetId,\n          parentWidgetId: currentSelection.parentWidgetId,\n          childId: currentSelection.childId,\n          elementKey: currentSelection.elementKey,\n          elementType: currentSelection.elementType,\n          wrapper,\n        };\n        try { e.dataTransfer.setData('text/plain', String(currentSelection.childId || currentSelection.elementKey || '')); } catch (_){ }\n        e.dataTransfer.effectAllowed = 'move';\n        wrapper.style.opacity = '0.6';\n        return;\n      }\n      const sec = target && target.closest && target.closest('[data-wto-section]');\n      if (!sec) return;\n      dragId = sec.dataset.wtoSection;\n      try { e.dataTransfer.setData('text/plain', dragId); } catch(_){ }\n      e.dataTransfer.effectAllowed = 'move';\n      sec.style.opacity = '0.4';\n    } catch (err) {\n      try { send('console', { level: 'error', args: [String(err && err.stack ? err.stack : err)] }); } catch(_){ }\n      console.error('wto-runtime dragstart error', err);\n    }\n  });\n"),
    'dragend': (r"document\.addEventListener\('dragend', e => \{[\s\S]*?\n  \}\);\n", 
"  document.addEventListener('dragend', e => {\n    try {\n      if (currentDragSource?.wrapper) currentDragSource.wrapper.style.opacity = '';\n      const sec = e.target.closest && e.target.closest('[data-wto-section]');\n      if (sec) sec.style.opacity = '';\n      e.preventDefault();\n      const l = document.getElementById('__wto_line'); if (l) l.remove();\n      currentDragSource = null;\n      currentDropTarget = null;\n    } catch (err) {\n      try { send('console', { level: 'error', args: [String(err && err.stack ? err.stack : err)] }); } catch(_){ }\n      console.error('wto-runtime dragend error', err);\n    }\n  });\n"),
    'dragover': (r"document\.addEventListener\('dragover', e => \{[\s\S]*?\n  \}\);\n", 
"  document.addEventListener('dragover', e => {\n    try {\n      const target = getEventTarget(e);\n      const candidate = target && target.closest ? target.closest('[data-container-child-wrapper], [data-wto-widget-element-key]') : null;\n      if (currentDragSource && candidate && currentDragSource.wrapper && candidate !== currentDragSource.wrapper && currentDragSource.wrapper.closest('[data-container-parent-widget-id], [data-wto-parent-widget-id]') && candidate.closest('[data-container-parent-widget-id], [data-wto-parent-widget-id]')) {\n        const r = candidate.getBoundingClientRect();\n        e.preventDefault();\n        let line = document.getElementById('__wto_line');\n        if (!line) { line = document.createElement('div'); line.id='__wto_line'; line.style.cssText='position:absolute;left:0;right:0;height:3px;background:#6366f1;z-index:9999;pointer-events:none;'; document.body.appendChild(line); }\n        const before = e.clientY < r.top + r.height / 2;\n        const top = before ? candidate.offsetTop : candidate.offsetTop + candidate.offsetHeight;\n        line.style.top = top + 'px';\n        currentDropTarget = { candidate, before };\n        return;\n      }\n      const sec = target && target.closest && target.closest('[data-wto-section]');\n      if (!sec || !dragId) return;\n      e.preventDefault();\n      const r = sec.getBoundingClientRect();\n      const before = e.clientY < r.top + r.height/2;\n      let line = document.getElementById('__wto_line');\n      if (!line) { line = document.createElement('div'); line.id='__wto_line'; line.style.cssText='position:absolute;left:0;right:0;height:3px;background:#6366f1;z-index:9999;pointer-events:none;'; document.body.appendChild(line); }\n      const top = before ? sec.offsetTop : sec.offsetTop + sec.offsetHeight;\n      line.style.top = top + 'px';\n      sec.dataset.wtoDropBefore = before ? '1' : '0';\n    } catch (err) {\n      try { send('console', { level: 'error', args: [String(err && err.stack ? err.stack : err)] }); } catch(_){ }\n      console.error('wto-runtime dragover error', err);\n    }\n  });\n"),
    'drop': (r"document\.addEventListener\('drop', e => \{[\s\S]*?\n  \}\);\n", 
"  document.addEventListener('drop', e => {\n    try {\n      const target = getEventTarget(e);\n      if (currentDragSource && currentDropTarget) {\n        const candidate = currentDropTarget.candidate;\n        const before = currentDropTarget.before;\n        const parent = candidate.closest('[data-container-parent-widget-id], [data-wto-parent-widget-id]');\n        const childId = candidate.getAttribute('data-container-child-id') || candidate.getAttribute('data-wto-child-id') || candidate.getAttribute('data-wto-widget-element-key');\n        const parentWidgetId = parent ? parent.getAttribute('data-container-parent-widget-id') || parent.getAttribute('data-wto-parent-widget-id') : null;\n        if (childId && currentDragSource.sectionId && currentDragSource.widgetId && parentWidgetId === currentDragSource.parentWidgetId) {\n          send('element-action', {\n            sectionId: currentDragSource.sectionId,\n            widgetId: currentDragSource.widgetId,\n            parentWidgetId: currentDragSource.parentWidgetId,\n            childId: currentDragSource.childId,\n            elementKey: currentDragSource.elementKey,\n            elementType: currentDragSource.elementType,\n            action: 'move',\n            targetChildId: childId,\n            before,\n          });\n          const l = document.getElementById('__wto_line'); if (l) l.remove();\n          currentDragSource.wrapper.style.opacity = '';\n          currentDragSource = null;\n          currentDropTarget = null;\n          return;\n        }\n      }\n      const sec = target && target.closest && target.closest('[data-wto-section]');\n      if (!sec || !dragId) return;\n      e.preventDefault();\n      const before = sec.dataset.wtoDropBefore === '1';\n      send('section-move', { fromId: dragId, toId: sec.dataset.wtoSection, before });\n      const l = document.getElementById('__wto_line'); if (l) l.remove();\n      dragId = null;\n    } catch (err) {\n      try { send('console', { level: 'error', args: [String(err && err.stack ? err.stack : err)] }); } catch(_){ }\n      console.error('wto-runtime drop error', err);\n    }\n  });\n")
}

for name, (pattern, repl) in replacements.items():
    new_text, count = re.subn(pattern, repl, text)
    if count == 0:
        raise SystemExit(f"pattern {name} not found")
    text = new_text

path.write_text(text, encoding='utf-8')
print('patched')
