import { createFileRoute } from "@tanstack/react-router";
import { useState, useMemo } from "react";
import { Search, Sparkles } from "lucide-react";
import { TEMPLATE_LIBRARY, type TemplateDefinition } from "@/lib/builder/templates";
import { useBuilder } from "@/lib/builder/store";
import { useNavigate } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { nanoid } from "nanoid";
import { createProject as createCloudProject } from "@/services/project";
import { saveBuilderProject } from "@/services/builderProject";
import { toast } from "sonner";

export const Route = createFileRoute("/dashboard/templates")({
  component: TemplatesPage,
});

const GALLERY_FILTERS = ["All", "Single page", "Multi page", "Free templates", "Premium templates"] as const;
type GalleryFilter = (typeof GALLERY_FILTERS)[number];

function TemplatesPage() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<GalleryFilter>("All");
  const [loading, setLoading] = useState<string | null>(null);
  const navigate = useNavigate();
  const newProject = useBuilder((s) => s.newProject);
  const applyTemplateToCurrent = useBuilder((s) => s.applyTemplate);

  const filteredTemplates = useMemo(() => {
    const search = query.trim().toLowerCase();
    return TEMPLATE_LIBRARY.filter((tpl) => {
      const matchesFilter =
        filter === "All" ||
        (filter === "Free templates" ? !tpl.isPremium :
          filter === "Premium templates" ? !!tpl.isPremium :
          (filter === "Single page" ? tpl.pageType === "single-page" :
           filter === "Multi page" ? tpl.pageType === "multi-page" : false));
      const matchesSearch =
        !search ||
        [tpl.name, tpl.description, tpl.category, tpl.pageType].join(" ").toLowerCase().includes(search);
      return matchesFilter && matchesSearch;
    });
  }, [filter, query]);

  const handleUseTemplate = async (tpl: TemplateDefinition) => {
    setLoading(tpl.id);
    try {
      // Create a new local builder project, apply the template so all IDs/metadata
      // are generated by the builder store, then persist the created project and
      // cloud metadata before navigating to the editor.
      const createdId = newProject(`${tpl.name}`);
      // applyTemplate mutates the current project in the builder store
      applyTemplateToCurrent(tpl as any);

      // Grab the fully-initialized project from the store and persist it
      const current = useBuilder.getState().currentProject();
      if (!current) throw new Error('Failed to initialize project from template');

      const now = Date.now();
      // Save builder project to Firestore (builderProjects collection)
      await saveBuilderProject(current);

      // Create cloud metadata
      await createCloudProject({
        id: current.id,
        name: current.name,
        templateId: tpl.id,
        thumbnail: current.thumbnail || tpl.thumbnail,
        description: current.description || tpl.description || "",
        favorite: false,
        status: "draft",
        isPublic: false,
        createdAt: current.createdAt ?? now,
        updatedAt: current.updatedAt ?? now,
        pages: (current.pages || []).map((p: any) => p.slug),
      });

      toast.success(`${tpl.name} template loaded! Opening editor...`);

      // Navigate to editor
      navigate({ to: "/editor/$projectId", params: { projectId: current.id } });
    } catch (err) {
      console.error("Template loading error:", err);
      toast.error("Failed to load template. Please try again.");
    } finally {
      setLoading(null);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 p-6">
      <div className="mx-auto max-w-7xl">
        {/* Header */}
        <div className="rounded-2xl bg-white p-6 shadow-sm mb-6">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-3">
                <h1 className="text-3xl font-bold text-slate-900">Templates</h1>
                <span className="inline-flex items-center gap-2 rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-amber-700">
                  <Sparkles className="h-3.5 w-3.5 text-amber-500" /> {TEMPLATE_LIBRARY.length} templates
                </span>
              </div>
              <p className="mt-2 text-slate-500">
                Browse and use professionally designed templates to get started quickly
              </p>
            </div>
          </div>
        </div>

        {/* Search and Filters */}
        <div className="rounded-2xl bg-white p-6 shadow-sm mb-6">
          <div className="space-y-4">
            <div className="relative">
              <Search className="pointer-events-none absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <input
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Search templates by name, category, or description..."
                className="w-full pl-12 pr-4 h-12 rounded-xl border border-slate-200 bg-white outline-none focus:ring-2 focus:ring-violet-500"
              />
            </div>

            <div className="flex flex-wrap gap-2">
              {GALLERY_FILTERS.map((filterOption) => (
                <button
                  key={filterOption}
                  onClick={() => setFilter(filterOption)}
                  className={`px-4 py-2 rounded-full text-sm font-medium transition ${
                    filter === filterOption
                      ? "bg-violet-600 text-white"
                      : "bg-slate-100 text-slate-700 hover:bg-slate-200"
                  }`}
                >
                  {filterOption}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Templates Grid */}
        <div>
          {filteredTemplates.length === 0 ? (
            <div className="rounded-2xl border-2 border-dashed border-slate-200 bg-white p-12 text-center">
              <p className="text-slate-600">No templates found matching your search. Try a different term or filter.</p>
            </div>
          ) : (
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {filteredTemplates.map((tpl) => (
                <div key={tpl.id} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg">
                  <div className="relative h-56 overflow-hidden bg-slate-100">
                    <img
                      src={tpl.thumbnail}
                      alt={tpl.name}
                      className="h-full w-full object-cover transition duration-300 group-hover:scale-105"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-black/20 to-transparent" />

                    {tpl.isPremium && (
                      <div className="absolute right-3 top-3 rounded-full bg-amber-500 px-3 py-1 text-xs font-semibold text-white">
                        Premium
                      </div>
                    )}

                    {tpl.category && (
                      <div className="absolute left-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.24em] text-slate-700">
                        {tpl.category}
                      </div>
                    )}
                  </div>

                  <div className="p-4">
                    <h3 className="text-lg font-semibold text-slate-900">{tpl.name}</h3>
                    <p className="mt-2 text-sm text-slate-600 line-clamp-2">{tpl.description}</p>

                    {tpl.pageType && (
                      <p className="mt-3 text-xs text-slate-500">
                        {tpl.pageType === "single-page" ? "Single Page" : "Multi Page"}
                      </p>
                    )}

                    <div className="mt-4">
                      <Button
                        onClick={() => handleUseTemplate(tpl)}
                        disabled={loading === tpl.id}
                        className="w-full bg-violet-600 text-white hover:bg-violet-700"
                      >
                        {loading === tpl.id ? "Loading..." : "Use Template"}
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}